# Generated by Django 5.2 on 2026-06-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100)),
                ('lift_type', models.CharField(choices=[('Passenger Lift', 'Passenger Lift'), ('Hospital Lift', 'Hospital Lift'), ('Home Lift', 'Home Lift'), ('Glass Lift', 'Glass Lift'), ('Goods Lift', 'Goods Lift'), ('Capsule Lift', 'Capsule Lift')], max_length=100)),
                ('building_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Hospital', 'Hospital'), ('Industrial', 'Industrial')], max_length=100)),
                ('floors', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
