# Generated by Django 5.2 on 2026-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('Passenger Lift', 'Passenger Lift'), ('Hospital Lift', 'Hospital Lift'), ('Home Lift', 'Home Lift'), ('Glass Lift', 'Glass Lift'), ('Goods Lift', 'Goods Lift'), ('Capsule Lift', 'Capsule Lift'), ('Automobile Lift', 'Automobile Lift'), ('MRL Lift', 'MRL Lift')], max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('short_description', models.TextField()),
                ('features', models.TextField(help_text='Enter features separated by commas')),
                ('capacity', models.CharField(help_text='Example: 6 Persons / 408 Kg', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
